plugin:
    name: 'zen.combine::lang.plugin.name'
    description: 'zen.combine::lang.plugin.description'
    author: 'Александр Аблизин'
    icon: oc-icon-rocket
    homepage: ''
permissions:
    zen.combine.open:
        tab: 'CSS combine'
        label: 'CSS combine access'
