plugin:
    name: 'zen.combine::lang.plugin.name'
    description: 'zen.combine::lang.plugin.description'
    author: 'Alexander Ablizin'
    icon: oc-icon-rocket
    homepage: 'https://october-studio.ru'
permissions:
    zen.combine.open:
        tab: 'CSS combine'
        label: 'CSS combine access'
